### PR TITLE
Create MultiplicationTable.py

### PR DESCRIPTION
**Pull request by Pakeetharan**
#28 Added Multiplication Table in Python

### CODE REVIEW

**Comment by KaisiGray** [comment]
@Pakeetharan i checked your program outputs but it's showing like this

Screenshot:-------

Screenshot_20221028-141042

But i want this output

how-to-print-table-in-java

**Comment by Pakeetharan** [comment]
> @Pakeetharan i checked your program outputs but it's showing like this
> 
> Screenshot:-------
> 
> Screenshot_20221028-141042
> 
> But i want this output
> 
> how-to-print-table-in-java

PR Updated, Kindly Check!

If this meets your requirement kindly merge and mark as "hacktoberfest-accepted"

**Comment by KaisiGray** [comment]
Everything is fine but pls remove first line of code .

**Comment by Pakeetharan** [comment]
@KaisiGray Done. Check now!

**Comment by KaisiGray** [comment]
Thank you @Pakeetharan for your contribution ❤️

**Comment by Pakeetharan** [comment]
@KaisiGray kindly mark/label this as "hacktoberfest-accepted", so that it'll be counted towards the challenge. Much appreciated. ❤️

**Pull request merged**
