### PR TITLE
Number Swapping using C lang is updated.

### PR DESCRIPTION
**Pull request by YTW7**
Number Swapping using C lang is updated.

### CODE REVIEW

**Comment by codingkush** [comment]
Thank you for contribution ❤️..

**Comment by KaisiGray** [comment]
@YTW7 I'll advise you that first ask for assigning issue..then you do contribution 

I hope you'll understand and do a great contribution in future

**Comment by YTW7** [comment]
Thank you for the kind advice @KaisiGray  :)

**Comment by KaisiGray** [comment]
😊👍🏻

**Pull request merged**
